[project]
name = "authentification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "flask-bcrypt>=1.0.1",
    "flask-jwt-extended>=4.7.1",
    "flask-mail>=0.10.0",
    "flask-sqlalchemy>=3.1.1",
    "phonenumbers>=8.13.53",
    "pillow>=11.1.0",
    "psycopg2-binary>=2.9.10",
    "pyotp>=2.9.0",
    "pytest>=8.3.4",
    "python-dotenv>=1.0.1",
    "pytz>=2024.2",
    "setuptools>=75.8.0",
    "twilio>=9.4.3",
]
